import type { AdsDataSource } from "@/data-access/contracts/ads-data-source.interface";
import type { AnnouncementDataSource } from "@/data-access/contracts/announcement-data-source.interface";
import type { AttributeDataSource } from "@/data-access/contracts/attribute-data-source.interface";
import type { BannerDataSource } from "@/data-access/contracts/banner-data-source.interface";
import type { BrandDataSource } from "@/data-access/contracts/brand-data-source.interface";
import type { CampaignDataSource } from "@/data-access/contracts/campaign-data-source.interface";
import type { CategoryDataSource } from "@/data-access/contracts/category-data-source.interface";
import type { ComboDataSource } from "@/data-access/contracts/combo-data-source.interface";
import type { EventDataSource } from "@/data-access/contracts/event-data-source.interface";
import type { MediaDataSource } from "@/data-access/contracts/media-data-source.interface";
import type { MenuDataSource } from "@/data-access/contracts/menu-data-source.interface";
import type { MetaDataSource } from "@/data-access/contracts/meta-data-source.interface";
import type { OptionsDataSource } from "@/data-access/contracts/options-data-source.interface";
import type { OrderDataSource } from "@/data-access/contracts/order-data-source.interface";
import type { PageDataSource } from "@/data-access/contracts/page-data-source.interface";
import type { PaymentDataSource } from "@/data-access/contracts/payment-data-source.interface";
import type { PostDataSource } from "@/data-access/contracts/post-data-source.interface";
import type { ProductDataSource } from "@/data-access/contracts/product-data-source.interface";
import type { PromotionDataSource } from "@/data-access/contracts/promotion-data-source.interface";
import type { ReviewDataSource } from "@/data-access/contracts/review-data-source.interface";
import type { SeoDataSource } from "@/data-access/contracts/seo-data-source.interface";
import type { StoreDataSource } from "@/data-access/contracts/store-data-source.interface";
import type { UserDataSource } from "@/data-access/contracts/user-data-source.interface";

export interface DataSources {
  page: PageDataSource;
  category: CategoryDataSource;
  brand: BrandDataSource;
  product: ProductDataSource;
  promotion: PromotionDataSource;
  menu: MenuDataSource;
  post: PostDataSource;
  event: EventDataSource;
  user: UserDataSource;
  store: StoreDataSource;
  banner: BannerDataSource;
  ads: AdsDataSource;
  combo: ComboDataSource;
  campaign: CampaignDataSource;
  announcement: AnnouncementDataSource;
  payment: PaymentDataSource;
  options: OptionsDataSource;
  media: MediaDataSource;
  order: OrderDataSource;
  review: ReviewDataSource;
  seo: SeoDataSource;
  meta: MetaDataSource;
  attribute: AttributeDataSource;
}
