export const MONGODB_COLLECTIONS = {
  pages: "pages",
  products: "products",
  categories: "categories",
  brands: "brands",
  promotions: "promotions",
  banners: "banners",
  menus: "menus",
  stores: "stores",
  storeRegions: "store_regions",
  storeLocations: "store_locations",
  media: "media",
  posts: "posts",
  events: "events",
  users: "users",
  orders: "orders",
  reviews: "reviews",
  ads: "ads",
  combos: "combos",
  campaigns: "campaigns",
  payments: "payments",
  announcements: "announcements",
  options: "options",
  seo: "seo",
} as const;
